name: uint-test-coverage

on:
  pull_request:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

jobs:
  generate-frontend-coverage:
    name: Generate client-app Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Run Jest tests with coverage
        run: yarn run test --coverage

      - name: Report Jest coverage to PR
        uses: adRise/jest-cov-reporter@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-summary-path: "./coverage/coverage-summary.json"
